
[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "efm-lsp-prettier" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "efm-lsp-prettier" ]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[[language]]
name = "go"
language-servers = ["gopls"]

# this does not seem to work
[[language]]
name = "cairo"
language-servers = ["scarb", "cairo-language-server", "cairo-language-server"]

[[language]]
name = "toml"
scope = "source.toml"
injection-regex = "toml"
file-types = ["toml", "poetry.lock", "Cargo.lock"]
comment-token = "#"
language-servers = [ "taplo" ]
#indent = { tab-width = 2, unit = "  " 




