name: CI

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    # Daily at 1:21
    - cron: '21 1 * * *'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm test
