# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: install tree-sitter
        run: npm install tree-sitter-cli@0.20

      - name: print tree-sitter version
        run: npx tree-sitter --version

      - name: generate the grammar
        run: npx tree-sitter generate

      - name: test
        run: npx tree-sitter test
