---
parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - prettier
rules:
  "no-control-regex": ["off"]
  "no-unused-vars": ["off"]
  "no-undef": ["off"]
