[[language]]
name = "typescript"
file-types = ["ts","js","tsx","jsx"]
auto-format = true
language-servers = ["tsserver"]

[language-server.tsserver]
command = "typescript-language-server"
args = ["--stdio"]
