blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions and Answers about v-analyzer
    url: https://github.com/v-analyzer/v-analyzer/discussions/categories/q-a
    about: You can ask and answer questions about v-analyzer in the discussions forum.

  - name: 💬 V Discord Server
    url: https://discord.gg/vlang
    about: You can join our Discord server for real time discussion and support
